In [1]:
import pandas as pd

# Load the dataset from a CSV file
data = pd.read_csv('/Users/irem/Desktop/TechLabs/data_model.csv')

# Print the first few rows of data
print(data.head())

print(data)

  year;month;day;mood;district;category;label;crowd_size_class
0  2024;February;16;Peaceful;Mitte;Environment;Cl...
1  2024;February;16;Peaceful;Mitte;War / Peace;In...
2  2024;February;15;with Intervention;Mitte;Envir...
3  2024;February;15;Peaceful;Mitte;Human Rights;A...
4  2024;February;14;with Intervention;Friedrichsh...
     year;month;day;mood;district;category;label;crowd_size_class
0     2024;February;16;Peaceful;Mitte;Environment;Cl...
1     2024;February;16;Peaceful;Mitte;War / Peace;In...
2     2024;February;15;with Intervention;Mitte;Envir...
3     2024;February;15;Peaceful;Mitte;Human Rights;A...
4     2024;February;14;with Intervention;Friedrichsh...
...                                                 ...
1102  2021;February;20;Peaceful;Mitte;Health;Coronav...
1103  2021;February;20;Peaceful;Mitte;Health;Coronav...
1104   2021;February;20;Peaceful;Berlin;Local;Housing;6
1105  2021;February;19;Peaceful;Mitte;Economy;Labor ...
1106  2021;February;19;Peaceful;Neukolln;Human Right...

[1107 rows x 1 columns]

In [8]:
import pandas as pd
import glob

all_data = pd.DataFrame()

for f in glob.glob("/Users/irem/Desktop/TechLabs/data_model.csv"):
    
    df = pd.read_csv(f,sep=";")
    
df

,year,month,day,mood,district,category,label,crowd_size_class
0,2024,February,16,Peaceful,Mitte,Environment,Climate,3
1,2024,February,16,Peaceful,Mitte,War / Peace,International,6
2,2024,February,15,with Intervention,Mitte,Environment,Climate,1
3,2024,February,15,Peaceful,Mitte,Human Rights,Against Racism,3
4,2024,February,14,with Intervention,Friedrichshain-Kreuzberg,War / Peace,International,4
...,...,...,...,...,...,...,...,...
1102,2021,February,20,Peaceful,Mitte,Health,Coronavirus,5
1103,2021,February,20,Peaceful,Mitte,Health,Coronavirus,5
1104,2021,February,20,Peaceful,Berlin,Local,Housing,6
1105,2021,February,19,Peaceful,Mitte,Economy,Labor Rights,4
1106,2021,February,19,Peaceful,Neukolln,Human Rights,Against Racism,6

In [9]:
df2 = pd.get_dummies(df)

In [10]:
df2

,year,crowd_size_class,month_April,month_August,month_December,month_February,month_February-January,month_January,month_July,month_June,...,label_Labor Rights,label_Migration,label_Nuclear,label_Other,label_Peace,label_Prison/Police,label_Rights,label_Transport,label_Violent,label_Womens Rights
0,2024,3,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2024,6,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2024,1,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2024,3,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2024,4,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,2021,5,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1103,2021,5,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1104,2021,6,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1105,2021,4,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
1106,2021,6,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
print(df2.dtypes)

year                   int64
crowd_size_class       int64
month_April             bool
month_August            bool
month_December          bool
                       ...
label_Prison/Police     bool
label_Rights            bool
label_Transport         bool
label_Violent           bool
label_Womens Rights     bool
Length: 99, dtype: object

In [13]:
df3 = df2.astype(int)

In [14]:
print(df3.dtypes)

year                   int64
crowd_size_class       int64
month_April            int64
month_August           int64
month_December         int64
                       ...
label_Prison/Police    int64
label_Rights           int64
label_Transport        int64
label_Violent          int64
label_Womens Rights    int64
Length: 99, dtype: object

In [15]:
df3

,year,crowd_size_class,month_April,month_August,month_December,month_February,month_February-January,month_January,month_July,month_June,...,label_Labor Rights,label_Migration,label_Nuclear,label_Other,label_Peace,label_Prison/Police,label_Rights,label_Transport,label_Violent,label_Womens Rights
0,2024,3,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2024,6,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2024,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2024,3,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2024,4,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,2021,5,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1103,2021,5,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1104,2021,6,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1105,2021,4,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1106,2021,6,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
print(list(df3.columns))

['year', 'crowd_size_class', 'month_April', 'month_August', 'month_December', 'month_February', 'month_February-January', 'month_January', 'month_July', 'month_June', 'month_March', 'month_May', 'month_November', 'month_October', 'month_September', 'day_1', 'day_10', 'day_11', 'day_12', 'day_13', 'day_14', 'day_15', 'day_16', 'day_16-1', 'day_17', 'day_18', 'day_19', 'day_2', 'day_20', 'day_21', 'day_22', 'day_23', 'day_24', 'day_25', 'day_26', 'day_27', 'day_28', 'day_29', 'day_3', 'day_30', 'day_31', 'day_4', 'day_5', 'day_6', 'day_7', 'day_8', 'day_9', 'mood_Peaceful', 'mood_Protest with intervention', 'mood_Violent', 'mood_with Intervention', 'district_Berlin', 'district_Berlin -Charlottenburg', 'district_Charlottenburg-Wilmersdorf', 'district_Friedrichshain-Kreuzberg', 'district_Lichtenberg', 'district_Marzahn-Hellersdorf', 'district_Mitte', 'district_Neukolln', 'district_Pankow', 'district_Reinickendorf', 'district_Spandau', 'district_Steglitz-Zehlendorf', 'district_Tempelhof-Schoneberg', 'district_Treptow-Kopenick', 'category_Economy', 'category_Environment', 'category_Health', 'category_Human Rights', 'category_Local', 'category_War / Peace', 'label_Against Environment ', 'label_Against Racism', 'label_Agriculture', 'label_Animal Rights', 'label_BLM', 'label_Cannabis', 'label_Climate', 'label_Coronavirus', 'label_Culture', 'label_Disability', 'label_Drug Use', 'label_Education', 'label_Energy', 'label_Finance', 'label_Housing', 'label_International', 'label_LGBTQ+', 'label_Labor Rights', 'label_Labor Rights ', 'label_Migration', 'label_Nuclear', 'label_Other', 'label_Peace', 'label_Prison/Police', 'label_Rights', 'label_Transport', 'label_Violent', 'label_Womens Rights']

In [19]:


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


X = df3[['year', 'month_April', 'month_August', 'month_December', 'month_February', 'month_February-January', 'month_January', 'month_July', 'month_June', 'month_March', 'month_May', 'month_November', 'month_October', 'month_September', 'day_1', 'day_10', 'day_11', 'day_12', 'day_13', 'day_14', 'day_15', 'day_16', 'day_16-1', 'day_17', 'day_18', 'day_19', 'day_2', 'day_20', 'day_21', 'day_22', 'day_23', 'day_24', 'day_25', 'day_26', 'day_27', 'day_28', 'day_29', 'day_3', 'day_30', 'day_31', 'day_4', 'day_5', 'day_6', 'day_7', 'day_8', 'day_9', 'mood_Peaceful', 'mood_Protest with intervention', 'mood_Violent', 'mood_with Intervention', 'district_Berlin', 'district_Berlin -Charlottenburg', 'district_Charlottenburg-Wilmersdorf', 'district_Friedrichshain-Kreuzberg', 'district_Lichtenberg', 'district_Marzahn-Hellersdorf', 'district_Mitte', 'district_Neukolln', 'district_Pankow', 'district_Reinickendorf', 'district_Spandau', 'district_Steglitz-Zehlendorf', 'district_Tempelhof-Schoneberg', 'district_Treptow-Kopenick', 'category_Economy', 'category_Environment', 'category_Health', 'category_Human Rights', 'category_Local', 'category_War / Peace', 'label_Against Environment ', 'label_Against Racism', 'label_Agriculture', 'label_Animal Rights', 'label_BLM', 'label_Cannabis', 'label_Climate', 'label_Coronavirus', 'label_Culture', 'label_Disability', 'label_Drug Use', 'label_Education', 'label_Energy', 'label_Finance', 'label_Housing', 'label_International', 'label_LGBTQ+', 'label_Labor Rights', 'label_Labor Rights ', 'label_Migration', 'label_Nuclear', 'label_Other', 'label_Peace', 'label_Prison/Police', 'label_Rights', 'label_Transport', 'label_Violent', 'label_Womens Rights']]


y = df['crowd_size_class']


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Logistic Regression model
model = LogisticRegression(max_iter=10000)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.36036036036036034